---
 - hosts: all
   vars:
     - app_dir: /home/ubuntu/oclapi/
   tasks:
   - name: Clone a oclapi github repository
     git:
       repo: https://github.com/OpenConceptLab/oclapi.git
       dest: "{{ app_dir }}"
       clone: yes
       update: yes

   - name: copy .env file
     copy:
       src: .env
       dest: "{{ app_dir }}/.env"

   - name: Build docker images and start the containers
     become: True
     shell:
      cmd: "docker-compose build && docker-compose up -d"
      chdir:  "{{ app_dir }}"